// Auto-generated inteface from api response
export interface Product {
  id: number;
  valueid: number;
  sku: string;
  thumbnailUrl: string;
  unlimited: boolean;
  inStock: boolean;
  name: string;
  price: number;
  priceInProductList: number;
  defaultDisplayedPrice: number;
  defaultDisplayedPriceFormatted: string;
  tax: {
    taxable: boolean;
    defaultLocationIncludedTaxRate: number;
    enabledManualTaxes: any[];
    taxClassCode: string;
  };
  lowestPriceSettings: {
    lowestPriceEnabled: boolean;
  };
  isShippingRequired: boolean;
  hasFreeShipping: boolean;
  url: string;
  autogeneratedSlug: string;
  customSlug: string;
  created: string;
  updated: string;
  createTimestamp: number;
  updateTimestamp: number;
  productClassId: number;
  enabled: boolean;
  options: {
    type: string;
    name: string;
    nameTranslated: {
      ru: string;
    };
    choices: {
      text: string;
      textTranslated: {
        ru: string;
      };
      priceModifier: number;
      priceModifierType: string;
    }[];
    defaultChoice: number;
    required: boolean;
  }[];
  fixedShippingRateOnly: boolean;
  fixedShippingRate: number;
  shipping: {
    type: string;
    methodMarkup: number;
    flatRate: number;
    disabledMethods: any[];
    enabledMethods: any[];
  };
  defaultCombinationId: number;
  imageUrl: string;
  smallThumbnailUrl: string;
  hdThumbnailUrl: string;
  originalImageUrl: string;
  originalImage: {
    url: string;
    width: number;
    height: number;
  };
  borderInfo: {
    dominatingColor: {
      red: number;
      green: number;
      blue: number;
      alpha: number;
    };
    homogeneity: boolean;
  };
  description: string;
  galleryImages: {
    id: number;
    url: string;
    thumbnail: string;
    originalImageUrl: string;
    imageUrl: string;
    hdThumbnailUrl: string;
    thumbnailUrl: string;
    smallThumbnailUrl: string;
    width: number;
    height: number;
    orderBy: number;
    borderInfo: {
      dominatingColor: {
        red: number;
        green: number;
        blue: number;
        alpha: number;
      };
      homogeneity: boolean;
    };
  }[];
  media: {
    images: {
      id: string;
      isMain: boolean;
      orderBy: number;
      image160pxUrl: string;
      image400pxUrl: string;
      image800pxUrl: string;
      image1500pxUrl: string;
      imageOriginalUrl: string;
    }[];
    videos: any[];
  };
  categoryIds: number[];
  categories: any[];
  defaultCategoryId: number;
  seoTitle: string;
  seoDescription: string;
  attributes: any[];
  relatedProducts: {
    productIds: number[];
    relatedCategory: {
      enabled: boolean;
      categoryId: number;
      productCount: number;
    };
  };
  combinations: any[];
  dimensions: {
    length: number;
    width: number;
    height: number;
  };
  volume: number;
  showOnFrontpage: number;
  isSampleProduct: boolean;
  googleItemCondition: string;
  isGiftCard: boolean;
  discountsAllowed: boolean;
  nameYourPriceEnabled: boolean;
}
